name: Development workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v3


      - name: On client directory
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
        working-directory: ./client
      - run: npm install
      - run: CI=false npm run build --if-present
      - run: cp -r build ../build


      - name: On root directory
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'utu-mike-react-tetris'
          heroku_email: 'mikko.j.syrjala@utu.fi'

  