name: Development workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17.x
    
      - name: On client directory
        working-directory: ./client
        run: npm install
       


      - name: On root directory
        run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'utu-mike-react-tetris'
          heroku_email: 'mikko.j.syrjala@utu.fi'