name: Development workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17.x
    
      - name: Client npm install
        working-directory: ./client
        run: npm install
       
      - name: Client npm build
        working-directory: ./client
        run: CI=false npm run build --if-present

      - name: Client copy build to root dir
        working-directory: ./client
        run: cp -r build ../build

      - name: Server npm install
        run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'utu-mike-react-tetris'
          heroku_email: 'mikko.j.syrjala@utu.fi'